name: Auto Deploy with Cache Buster

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout du code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_PAT }}

      - name: Générer un cache buster (timestamp)
        run: |
          echo "<!-- cache-buster: $(date +%s) -->" >> index.html

      - name: Commit auto avec cache buster
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add index.html
          git commit -m "Auto: cache buster"
          git push origin main
